### ISSUE TITLE
Install breaks for some users requiring them to reinstall

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#104]
The result of the below log was that users had to reinstall to get their cadesim running.

thoughts/notes:
* Local version was: 109927
* New version was: 20201031153845
* identical user code was uploaded on both imfast and github
* install switched from using https://gucadesim.imfast.io/ to https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/
* The error message appears: ```WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]``` when [target version is <= version ](https://github.com/threerings/getdown/blob/55c544c68b8ee55a72a048f796ba4f1441bf7437/core/src/main/java/com/threerings/getdown/data/Application.java#L463)
* the new version 20201031153845 is too long for an int32. however it's fine for an int64 (java Long) and the code [uses Longs](https://github.com/threerings/getdown/blob/55c544c68b8ee55a72a048f796ba4f1441bf7437/core/src/main/java/com/threerings/getdown/data/Application.java#L1267) to process versions.
* I think this might be solveable if we moved to a non versioned app - besides there are not that many files to verify.
```
2020/11/01 17:36:26:363 INFO Getdown starting [version=1.8.6, built=2019-06-04 15:27]
2020/11/01 17:36:26:363 INFO Checking whether we need to use a proxy...
2020/11/01 17:36:26:380 INFO Failed to find proxy settings in Windows registry [error=java.lang.UnsatisfiedLinkError: no jRegistryKey in java.library.path]
2020/11/01 17:36:26:511 INFO Attempting to fetch without proxy: https://gucadesim.imfast.io/getdown.txt
2020/11/01 17:36:28:263 INFO No proxy appears to be needed.
2020/11/01 17:36:28:267 INFO Able to lock for updates: true
2020/11/01 17:36:28:267 INFO Verifying application: https://gucadesim.imfast.io/
2020/11/01 17:36:28:268 INFO Version: 109927
2020/11/01 17:36:28:268 INFO Class: com.benberi.cadesim.desktop.DesktopLauncher
2020/11/01 17:36:28:268 INFO Failed to load digest: C:\Users\user1\Desktop\GU CadeSim\digest2.txt (The system cannot find the file specified). Attempting recovery...
2020/11/01 17:36:28:269 INFO Attempting to refetch 'digest.txt' from 'https://gucadesim.imfast.io/digest.txt'.
2020/11/01 17:36:28:627 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:28:628 INFO Attempting to refetch 'digest2.txt' from 'https://gucadesim.imfast.io/digest2.txt'.
2020/11/01 17:36:29:014 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:29:016 INFO Resource failed digest check [rsrc=getdown.txt, computed=171614c1d897b79a7af9526edb4adb1534c3f9282fec07678f8d89e9d0167455, expected=4110e2cdf80968511a9b9306f0f1191d6419978d759f2bee621540ce107721ea]
2020/11/01 17:36:29:017 INFO Attempting to refetch 'getdown.txt' from 'https://gucadesim.imfast.io/getdown.txt'.
2020/11/01 17:36:29:097 INFO Attempting to refetch 'digest.txt' from 'https://gucadesim.imfast.io/digest.txt'.
2020/11/01 17:36:29:154 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:29:157 INFO Attempting to refetch 'digest2.txt' from 'https://gucadesim.imfast.io/digest2.txt'.
2020/11/01 17:36:29:223 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:29:232 INFO Application requires update.
2020/11/01 17:36:29:233 WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]
2020/11/01 17:36:29:233 INFO Attempting to refetch 'digest.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest.txt'.
2020/11/01 17:36:29:577 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:29:580 INFO Attempting to refetch 'digest2.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest2.txt'.
2020/11/01 17:36:29:723 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:29:726 INFO Attempting to refetch 'getdown.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/getdown.txt'.
2020/11/01 17:36:29:875 INFO Verifying application: https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/
2020/11/01 17:36:29:875 INFO Version: 20201031153845
2020/11/01 17:36:29:875 INFO Class: com.benberi.cadesim.desktop.DesktopLauncher
2020/11/01 17:36:29:876 INFO Application requires update.
2020/11/01 17:36:29:877 WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]
2020/11/01 17:36:29:877 INFO Attempting to refetch 'digest.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest.txt'.
2020/11/01 17:36:29:934 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:29:936 INFO Attempting to refetch 'digest2.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest2.txt'.
2020/11/01 17:36:29:971 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:29:974 INFO Attempting to refetch 'getdown.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/getdown.txt'.
2020/11/01 17:36:30:023 INFO Verifying application: https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/
2020/11/01 17:36:30:023 INFO Version: 20201031153845
2020/11/01 17:36:30:023 INFO Class: com.benberi.cadesim.desktop.DesktopLauncher
2020/11/01 17:36:30:024 INFO Application requires update.
2020/11/01 17:36:30:025 WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]
2020/11/01 17:36:30:025 INFO Attempting to refetch 'digest.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest.txt'.
2020/11/01 17:36:30:066 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:30:069 INFO Attempting to refetch 'digest2.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest2.txt'.
2020/11/01 17:36:30:101 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:30:104 INFO Attempting to refetch 'getdown.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/getdown.txt'.
2020/11/01 17:36:30:143 INFO Verifying application: https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/
2020/11/01 17:36:30:143 INFO Version: 20201031153845
2020/11/01 17:36:30:143 INFO Class: com.benberi.cadesim.desktop.DesktopLauncher
2020/11/01 17:36:30:144 INFO Application requires update.
2020/11/01 17:36:30:145 WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]
2020/11/01 17:36:30:145 INFO Attempting to refetch 'digest.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest.txt'.
2020/11/01 17:36:30:183 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:30:186 INFO Attempting to refetch 'digest2.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest2.txt'.
2020/11/01 17:36:30:217 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:30:220 INFO Attempting to refetch 'getdown.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/getdown.txt'.
2020/11/01 17:36:30:259 INFO Verifying application: https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/
2020/11/01 17:36:30:259 INFO Version: 20201031153845
2020/11/01 17:36:30:259 INFO Class: com.benberi.cadesim.desktop.DesktopLauncher
2020/11/01 17:36:30:260 INFO Application requires update.
2020/11/01 17:36:30:261 WARNING Requested patch resource for up-to-date or non-versioned application [cvers=20201031153845, tvers=109927]
2020/11/01 17:36:30:261 INFO Attempting to refetch 'digest.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest.txt'.
2020/11/01 17:36:30:304 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2020/11/01 17:36:30:306 INFO Attempting to refetch 'digest2.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/digest2.txt'.
2020/11/01 17:36:30:346 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2020/11/01 17:36:30:349 INFO Attempting to refetch 'getdown.txt' from 'https://plaza-in-a-heatwave.github.io/Cadesim/growup/client/http/getdown.txt'.
2020/11/01 17:36:30:401 WARNING Pants! We couldn't get the job done.
2020/11/01 17:36:30:402 WARNING getdown() failed.
java.io.IOException: m.unable_to_repair
	at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
	at com.threerings.getdown.launcher.a.run(Unknown Source)
2020/11/01 17:36:30:406 INFO Releasing lock
```

**Comment by plaza-in-a-heatwave** [comment]
This doesn't appear to be related to the similar bug where getdown fails to verify due to line endings.

**Comment by mdjong1** [comment]
https://github.com/threerings/getdown/issues/158

**Comment by plaza-in-a-heatwave** [comment]
> 
> 
> [threerings/getdown#158](https://github.com/threerings/getdown/issues/158)

Cheers but it looks like this is a different problem... I haven't seen any warnings for getdown.txt failing to validate (but have come across that issue a few times in testing). the digest hashes on the server should be fine as they are computed from the build script and the files are not changed after that.

**Comment by plaza-in-a-heatwave** [comment]
Assuming that #108 fixes this issue as it kills the specific error - will open up a separate issue if there is a new bug.
